//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.10 at 08:21:10 PM EDT 
//


package cac;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cac package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ImsiRemapperRuleConfigImsiRemappingsImsiRemappingReMappedImsi_QNAME = new QName("", "reMappedImsi");
    private final static QName _ImsiRemapperRuleConfigImsiRemappingsImsiRemappingImsiPattern_QNAME = new QName("", "imsiPattern");
    private final static QName _EntitlementRuleConfigRealmsRealmRealmRule_QNAME = new QName("", "realmRule");
    private final static QName _ImsiRemapperRuleConfigImsiRemappings_QNAME = new QName("", "imsiRemappings");
    private final static QName _RuleSetRuleRuleStyle_QNAME = new QName("", "RuleStyle");
    private final static QName _RuleSetRuleExpression_QNAME = new QName("", "Expression");
    private final static QName _RuleSetRulePriority_QNAME = new QName("", "Priority");
    private final static QName _RuleSetRuleAvailable_QNAME = new QName("", "Available");
    private final static QName _RuleSetRuleResultType_QNAME = new QName("", "ResultType");
    private final static QName _EntitlementRuleConfigRealmsRealm_QNAME = new QName("", "realm");
    private final static QName _AddressURLConfigAddressStatusErrorMappingsMappingErrorCode_QNAME = new QName("", "errorCode");
    private final static QName _AddressURLConfigAddressStatusErrorMappingsMappingAddressStatus_QNAME = new QName("", "addressStatus");
    private final static QName _AddressURLConfigUrlMappingsUrlMapping_QNAME = new QName("", "urlMapping");
    private final static QName _RuleBindingSetBindingRuleId_QNAME = new QName("", "RuleId");
    private final static QName _RuleBindingSetBindingEventName_QNAME = new QName("", "EventName");
    private final static QName _RuleBindingSetBindingApplicationID_QNAME = new QName("", "ApplicationID");
    private final static QName _AddressURLConfigUrlMappingsUrlMappingAddressStatus_QNAME = new QName("", "address-status");
    private final static QName _AddressURLConfigUrlMappingsUrlMappingTcStatus_QNAME = new QName("", "tc-status");
    private final static QName _AddressURLConfigUrlMappingsUrlMappingUrl_QNAME = new QName("", "url");
    private final static QName _AddressURLConfigAddressStatusErrorMappingsMapping_QNAME = new QName("", "mapping");
    private final static QName _RuleSetRule_QNAME = new QName("", "Rule");
    private final static QName _RuleBindingSetBinding_QNAME = new QName("", "Binding");
    private final static QName _ImsiRemapperRuleConfigImsiRemappingsImsiRemapping_QNAME = new QName("", "imsiRemapping");
    private final static QName _AddressURLConfigDefaultAddressStatus_QNAME = new QName("", "defaultAddressStatus");
    private final static QName _AddressURLConfigAddressStatusErrorMappings_QNAME = new QName("", "addressStatusErrorMappings");
    private final static QName _AddressURLConfigDefaultAddressURL_QNAME = new QName("", "defaultAddressURL");
    private final static QName _AddressURLConfigUrlMappings_QNAME = new QName("", "urlMappings");
    private final static QName _EntitlementRuleConfigRealms_QNAME = new QName("", "realms");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cac
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddressURLConfig }
     * 
     */
    public AddressURLConfig createAddressURLConfig() {
        return new AddressURLConfig();
    }

    /**
     * Create an instance of {@link RuleSet }
     * 
     */
    public RuleSet createRuleSet() {
        return new RuleSet();
    }

    /**
     * Create an instance of {@link EntitlementRuleConfig }
     * 
     */
    public EntitlementRuleConfig createEntitlementRuleConfig() {
        return new EntitlementRuleConfig();
    }

    /**
     * Create an instance of {@link ImsiRemapperRuleConfig }
     * 
     */
    public ImsiRemapperRuleConfig createImsiRemapperRuleConfig() {
        return new ImsiRemapperRuleConfig();
    }

    /**
     * Create an instance of {@link RuleBindingSet }
     * 
     */
    public RuleBindingSet createRuleBindingSet() {
        return new RuleBindingSet();
    }

    /**
     * Create an instance of {@link ImsiRemapperRuleConfig.ImsiRemappings }
     * 
     */
    public ImsiRemapperRuleConfig.ImsiRemappings createImsiRemapperRuleConfigImsiRemappings() {
        return new ImsiRemapperRuleConfig.ImsiRemappings();
    }

    /**
     * Create an instance of {@link EntitlementRuleConfig.Realms }
     * 
     */
    public EntitlementRuleConfig.Realms createEntitlementRuleConfigRealms() {
        return new EntitlementRuleConfig.Realms();
    }

    /**
     * Create an instance of {@link EntitlementRuleConfig.Realms.Realm }
     * 
     */
    public EntitlementRuleConfig.Realms.Realm createEntitlementRuleConfigRealmsRealm() {
        return new EntitlementRuleConfig.Realms.Realm();
    }

    /**
     * Create an instance of {@link AddressURLConfig.AddressStatusErrorMappings }
     * 
     */
    public AddressURLConfig.AddressStatusErrorMappings createAddressURLConfigAddressStatusErrorMappings() {
        return new AddressURLConfig.AddressStatusErrorMappings();
    }

    /**
     * Create an instance of {@link AddressURLConfig.UrlMappings }
     * 
     */
    public AddressURLConfig.UrlMappings createAddressURLConfigUrlMappings() {
        return new AddressURLConfig.UrlMappings();
    }

    /**
     * Create an instance of {@link RuleSet.Rule }
     * 
     */
    public RuleSet.Rule createRuleSetRule() {
        return new RuleSet.Rule();
    }

    /**
     * Create an instance of {@link RuleBindingSet.Binding }
     * 
     */
    public RuleBindingSet.Binding createRuleBindingSetBinding() {
        return new RuleBindingSet.Binding();
    }

    /**
     * Create an instance of {@link ImsiRemapperRuleConfig.ImsiRemappings.ImsiRemapping }
     * 
     */
    public ImsiRemapperRuleConfig.ImsiRemappings.ImsiRemapping createImsiRemapperRuleConfigImsiRemappingsImsiRemapping() {
        return new ImsiRemapperRuleConfig.ImsiRemappings.ImsiRemapping();
    }

    /**
     * Create an instance of {@link EntitlementRuleConfig.Realms.Realm.RealmRule }
     * 
     */
    public EntitlementRuleConfig.Realms.Realm.RealmRule createEntitlementRuleConfigRealmsRealmRealmRule() {
        return new EntitlementRuleConfig.Realms.Realm.RealmRule();
    }

    /**
     * Create an instance of {@link AddressURLConfig.AddressStatusErrorMappings.Mapping }
     * 
     */
    public AddressURLConfig.AddressStatusErrorMappings.Mapping createAddressURLConfigAddressStatusErrorMappingsMapping() {
        return new AddressURLConfig.AddressStatusErrorMappings.Mapping();
    }

    /**
     * Create an instance of {@link AddressURLConfig.UrlMappings.UrlMapping }
     * 
     */
    public AddressURLConfig.UrlMappings.UrlMapping createAddressURLConfigUrlMappingsUrlMapping() {
        return new AddressURLConfig.UrlMappings.UrlMapping();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reMappedImsi", scope = ImsiRemapperRuleConfig.ImsiRemappings.ImsiRemapping.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createImsiRemapperRuleConfigImsiRemappingsImsiRemappingReMappedImsi(String value) {
        return new JAXBElement<String>(_ImsiRemapperRuleConfigImsiRemappingsImsiRemappingReMappedImsi_QNAME, String.class, ImsiRemapperRuleConfig.ImsiRemappings.ImsiRemapping.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "imsiPattern", scope = ImsiRemapperRuleConfig.ImsiRemappings.ImsiRemapping.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createImsiRemapperRuleConfigImsiRemappingsImsiRemappingImsiPattern(String value) {
        return new JAXBElement<String>(_ImsiRemapperRuleConfigImsiRemappingsImsiRemappingImsiPattern_QNAME, String.class, ImsiRemapperRuleConfig.ImsiRemappings.ImsiRemapping.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EntitlementRuleConfig.Realms.Realm.RealmRule }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "realmRule", scope = EntitlementRuleConfig.Realms.Realm.class)
    public JAXBElement<EntitlementRuleConfig.Realms.Realm.RealmRule> createEntitlementRuleConfigRealmsRealmRealmRule(EntitlementRuleConfig.Realms.Realm.RealmRule value) {
        return new JAXBElement<EntitlementRuleConfig.Realms.Realm.RealmRule>(_EntitlementRuleConfigRealmsRealmRealmRule_QNAME, EntitlementRuleConfig.Realms.Realm.RealmRule.class, EntitlementRuleConfig.Realms.Realm.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImsiRemapperRuleConfig.ImsiRemappings }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "imsiRemappings", scope = ImsiRemapperRuleConfig.class)
    public JAXBElement<ImsiRemapperRuleConfig.ImsiRemappings> createImsiRemapperRuleConfigImsiRemappings(ImsiRemapperRuleConfig.ImsiRemappings value) {
        return new JAXBElement<ImsiRemapperRuleConfig.ImsiRemappings>(_ImsiRemapperRuleConfigImsiRemappings_QNAME, ImsiRemapperRuleConfig.ImsiRemappings.class, ImsiRemapperRuleConfig.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RuleStyle", scope = RuleSet.Rule.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createRuleSetRuleRuleStyle(String value) {
        return new JAXBElement<String>(_RuleSetRuleRuleStyle_QNAME, String.class, RuleSet.Rule.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Expression", scope = RuleSet.Rule.class)
    public JAXBElement<String> createRuleSetRuleExpression(String value) {
        return new JAXBElement<String>(_RuleSetRuleExpression_QNAME, String.class, RuleSet.Rule.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Priority", scope = RuleSet.Rule.class)
    public JAXBElement<Integer> createRuleSetRulePriority(Integer value) {
        return new JAXBElement<Integer>(_RuleSetRulePriority_QNAME, Integer.class, RuleSet.Rule.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Available", scope = RuleSet.Rule.class)
    public JAXBElement<Boolean> createRuleSetRuleAvailable(Boolean value) {
        return new JAXBElement<Boolean>(_RuleSetRuleAvailable_QNAME, Boolean.class, RuleSet.Rule.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ResultType", scope = RuleSet.Rule.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createRuleSetRuleResultType(String value) {
        return new JAXBElement<String>(_RuleSetRuleResultType_QNAME, String.class, RuleSet.Rule.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EntitlementRuleConfig.Realms.Realm }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "realm", scope = EntitlementRuleConfig.Realms.class)
    public JAXBElement<EntitlementRuleConfig.Realms.Realm> createEntitlementRuleConfigRealmsRealm(EntitlementRuleConfig.Realms.Realm value) {
        return new JAXBElement<EntitlementRuleConfig.Realms.Realm>(_EntitlementRuleConfigRealmsRealm_QNAME, EntitlementRuleConfig.Realms.Realm.class, EntitlementRuleConfig.Realms.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "errorCode", scope = AddressURLConfig.AddressStatusErrorMappings.Mapping.class)
    public JAXBElement<Integer> createAddressURLConfigAddressStatusErrorMappingsMappingErrorCode(Integer value) {
        return new JAXBElement<Integer>(_AddressURLConfigAddressStatusErrorMappingsMappingErrorCode_QNAME, Integer.class, AddressURLConfig.AddressStatusErrorMappings.Mapping.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "addressStatus", scope = AddressURLConfig.AddressStatusErrorMappings.Mapping.class)
    public JAXBElement<Integer> createAddressURLConfigAddressStatusErrorMappingsMappingAddressStatus(Integer value) {
        return new JAXBElement<Integer>(_AddressURLConfigAddressStatusErrorMappingsMappingAddressStatus_QNAME, Integer.class, AddressURLConfig.AddressStatusErrorMappings.Mapping.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressURLConfig.UrlMappings.UrlMapping }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "urlMapping", scope = AddressURLConfig.UrlMappings.class)
    public JAXBElement<AddressURLConfig.UrlMappings.UrlMapping> createAddressURLConfigUrlMappingsUrlMapping(AddressURLConfig.UrlMappings.UrlMapping value) {
        return new JAXBElement<AddressURLConfig.UrlMappings.UrlMapping>(_AddressURLConfigUrlMappingsUrlMapping_QNAME, AddressURLConfig.UrlMappings.UrlMapping.class, AddressURLConfig.UrlMappings.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RuleId", scope = RuleBindingSet.Binding.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createRuleBindingSetBindingRuleId(String value) {
        return new JAXBElement<String>(_RuleBindingSetBindingRuleId_QNAME, String.class, RuleBindingSet.Binding.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EventName", scope = RuleBindingSet.Binding.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createRuleBindingSetBindingEventName(String value) {
        return new JAXBElement<String>(_RuleBindingSetBindingEventName_QNAME, String.class, RuleBindingSet.Binding.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ApplicationID", scope = RuleBindingSet.Binding.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createRuleBindingSetBindingApplicationID(String value) {
        return new JAXBElement<String>(_RuleBindingSetBindingApplicationID_QNAME, String.class, RuleBindingSet.Binding.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "address-status", scope = AddressURLConfig.UrlMappings.UrlMapping.class)
    public JAXBElement<Integer> createAddressURLConfigUrlMappingsUrlMappingAddressStatus(Integer value) {
        return new JAXBElement<Integer>(_AddressURLConfigUrlMappingsUrlMappingAddressStatus_QNAME, Integer.class, AddressURLConfig.UrlMappings.UrlMapping.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "imsiPattern", scope = AddressURLConfig.UrlMappings.UrlMapping.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createAddressURLConfigUrlMappingsUrlMappingImsiPattern(String value) {
        return new JAXBElement<String>(_ImsiRemapperRuleConfigImsiRemappingsImsiRemappingImsiPattern_QNAME, String.class, AddressURLConfig.UrlMappings.UrlMapping.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tc-status", scope = AddressURLConfig.UrlMappings.UrlMapping.class)
    public JAXBElement<Integer> createAddressURLConfigUrlMappingsUrlMappingTcStatus(Integer value) {
        return new JAXBElement<Integer>(_AddressURLConfigUrlMappingsUrlMappingTcStatus_QNAME, Integer.class, AddressURLConfig.UrlMappings.UrlMapping.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "url", scope = AddressURLConfig.UrlMappings.UrlMapping.class)
    public JAXBElement<String> createAddressURLConfigUrlMappingsUrlMappingUrl(String value) {
        return new JAXBElement<String>(_AddressURLConfigUrlMappingsUrlMappingUrl_QNAME, String.class, AddressURLConfig.UrlMappings.UrlMapping.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressURLConfig.AddressStatusErrorMappings.Mapping }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mapping", scope = AddressURLConfig.AddressStatusErrorMappings.class)
    public JAXBElement<AddressURLConfig.AddressStatusErrorMappings.Mapping> createAddressURLConfigAddressStatusErrorMappingsMapping(AddressURLConfig.AddressStatusErrorMappings.Mapping value) {
        return new JAXBElement<AddressURLConfig.AddressStatusErrorMappings.Mapping>(_AddressURLConfigAddressStatusErrorMappingsMapping_QNAME, AddressURLConfig.AddressStatusErrorMappings.Mapping.class, AddressURLConfig.AddressStatusErrorMappings.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RuleSet.Rule }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Rule", scope = RuleSet.class)
    public JAXBElement<RuleSet.Rule> createRuleSetRule(RuleSet.Rule value) {
        return new JAXBElement<RuleSet.Rule>(_RuleSetRule_QNAME, RuleSet.Rule.class, RuleSet.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RuleBindingSet.Binding }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Binding", scope = RuleBindingSet.class)
    public JAXBElement<RuleBindingSet.Binding> createRuleBindingSetBinding(RuleBindingSet.Binding value) {
        return new JAXBElement<RuleBindingSet.Binding>(_RuleBindingSetBinding_QNAME, RuleBindingSet.Binding.class, RuleBindingSet.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImsiRemapperRuleConfig.ImsiRemappings.ImsiRemapping }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "imsiRemapping", scope = ImsiRemapperRuleConfig.ImsiRemappings.class)
    public JAXBElement<ImsiRemapperRuleConfig.ImsiRemappings.ImsiRemapping> createImsiRemapperRuleConfigImsiRemappingsImsiRemapping(ImsiRemapperRuleConfig.ImsiRemappings.ImsiRemapping value) {
        return new JAXBElement<ImsiRemapperRuleConfig.ImsiRemappings.ImsiRemapping>(_ImsiRemapperRuleConfigImsiRemappingsImsiRemapping_QNAME, ImsiRemapperRuleConfig.ImsiRemappings.ImsiRemapping.class, ImsiRemapperRuleConfig.ImsiRemappings.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "defaultAddressStatus", scope = AddressURLConfig.class)
    public JAXBElement<Integer> createAddressURLConfigDefaultAddressStatus(Integer value) {
        return new JAXBElement<Integer>(_AddressURLConfigDefaultAddressStatus_QNAME, Integer.class, AddressURLConfig.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressURLConfig.AddressStatusErrorMappings }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "addressStatusErrorMappings", scope = AddressURLConfig.class)
    public JAXBElement<AddressURLConfig.AddressStatusErrorMappings> createAddressURLConfigAddressStatusErrorMappings(AddressURLConfig.AddressStatusErrorMappings value) {
        return new JAXBElement<AddressURLConfig.AddressStatusErrorMappings>(_AddressURLConfigAddressStatusErrorMappings_QNAME, AddressURLConfig.AddressStatusErrorMappings.class, AddressURLConfig.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "defaultAddressURL", scope = AddressURLConfig.class)
    public JAXBElement<String> createAddressURLConfigDefaultAddressURL(String value) {
        return new JAXBElement<String>(_AddressURLConfigDefaultAddressURL_QNAME, String.class, AddressURLConfig.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressURLConfig.UrlMappings }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "urlMappings", scope = AddressURLConfig.class)
    public JAXBElement<AddressURLConfig.UrlMappings> createAddressURLConfigUrlMappings(AddressURLConfig.UrlMappings value) {
        return new JAXBElement<AddressURLConfig.UrlMappings>(_AddressURLConfigUrlMappings_QNAME, AddressURLConfig.UrlMappings.class, AddressURLConfig.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EntitlementRuleConfig.Realms }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "realms", scope = EntitlementRuleConfig.class)
    public JAXBElement<EntitlementRuleConfig.Realms> createEntitlementRuleConfigRealms(EntitlementRuleConfig.Realms value) {
        return new JAXBElement<EntitlementRuleConfig.Realms>(_EntitlementRuleConfigRealms_QNAME, EntitlementRuleConfig.Realms.class, EntitlementRuleConfig.class, value);
    }

}
